version: '3.4'
services:
  api:
    build: .
    container_name: shipping_quotation_service
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - database
    networks:
      - web
      
  database:
    image: postgres:13-alpine
    container_name: database
    volumes:
      - "db-data:/var/lib/postgresql/data"
    ports:
      - 5432:5432
    env_file:
      - ./db.env
    networks:
      - web

volumes:
  db-data:

networks:
  web:
    driver: bridge