name: Testing

on:
  pull_request:
    branches:
      - main
      - dev
  workflow_call:

jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: '1.3.2'

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'poetry'

      - name: Install requirements
        run: poetry install --with test

      - name: Run unit-tests
        run: |
          set -o pipefail
          poetry run make unit-test-cov-fail